/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.mymix;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cup</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.mymix.Cup#getCup <em>Cup</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.mymix.MymixPackage#getCup()
 * @model
 * @generated
 */
public interface Cup extends EObject
{
  /**
   * Returns the value of the '<em><b>Cup</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Cup</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cup</em>' attribute.
   * @see #setCup(int)
   * @see org.xtext.example.mydsl.mymix.MymixPackage#getCup_Cup()
   * @model
   * @generated
   */
  int getCup();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.mymix.Cup#getCup <em>Cup</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cup</em>' attribute.
   * @see #getCup()
   * @generated
   */
  void setCup(int value);

} // Cup
