/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.mymix;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.mymix.MymixFactory
 * @model kind="package"
 * @generated
 */
public interface MymixPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "mymix";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/Mymix";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "mymix";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MymixPackage eINSTANCE = org.xtext.example.mydsl.mymix.impl.MymixPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.mymix.impl.DeviceImpl <em>Device</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.mymix.impl.DeviceImpl
   * @see org.xtext.example.mydsl.mymix.impl.MymixPackageImpl#getDevice()
   * @generated
   */
  int DEVICE = 0;

  /**
   * The feature id for the '<em><b>Procedures</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEVICE__PROCEDURES = 0;

  /**
   * The number of structural features of the '<em>Device</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEVICE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.mymix.impl.ProcedureImpl <em>Procedure</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.mymix.impl.ProcedureImpl
   * @see org.xtext.example.mydsl.mymix.impl.MymixPackageImpl#getProcedure()
   * @generated
   */
  int PROCEDURE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCEDURE__NAME = 0;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCEDURE__BODY = 1;

  /**
   * The feature id for the '<em><b>Result</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCEDURE__RESULT = 2;

  /**
   * The number of structural features of the '<em>Procedure</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCEDURE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.mymix.impl.OperationImpl <em>Operation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.mymix.impl.OperationImpl
   * @see org.xtext.example.mydsl.mymix.impl.MymixPackageImpl#getOperation()
   * @generated
   */
  int OPERATION = 2;

  /**
   * The number of structural features of the '<em>Operation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.mymix.impl.TakeStuffImpl <em>Take Stuff</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.mymix.impl.TakeStuffImpl
   * @see org.xtext.example.mydsl.mymix.impl.MymixPackageImpl#getTakeStuff()
   * @generated
   */
  int TAKE_STUFF = 3;

  /**
   * The feature id for the '<em><b>Op</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TAKE_STUFF__OP = OPERATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TAKE_STUFF__BODY = OPERATION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Take Stuff</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TAKE_STUFF_FEATURE_COUNT = OPERATION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.mymix.impl.TakeImpl <em>Take</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.mymix.impl.TakeImpl
   * @see org.xtext.example.mydsl.mymix.impl.MymixPackageImpl#getTake()
   * @generated
   */
  int TAKE = 4;

  /**
   * The feature id for the '<em><b>Quantity</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TAKE__QUANTITY = 0;

  /**
   * The feature id for the '<em><b>Cup</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TAKE__CUP = 1;

  /**
   * The feature id for the '<em><b>Filter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TAKE__FILTER = 2;

  /**
   * The number of structural features of the '<em>Take</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TAKE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.mymix.impl.PutSomeImpl <em>Put Some</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.mymix.impl.PutSomeImpl
   * @see org.xtext.example.mydsl.mymix.impl.MymixPackageImpl#getPutSome()
   * @generated
   */
  int PUT_SOME = 5;

  /**
   * The feature id for the '<em><b>Wait</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PUT_SOME__WAIT = 0;

  /**
   * The feature id for the '<em><b>Put</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PUT_SOME__PUT = 1;

  /**
   * The number of structural features of the '<em>Put Some</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PUT_SOME_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.mymix.impl.PutAllImpl <em>Put All</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.mymix.impl.PutAllImpl
   * @see org.xtext.example.mydsl.mymix.impl.MymixPackageImpl#getPutAll()
   * @generated
   */
  int PUT_ALL = 6;

  /**
   * The feature id for the '<em><b>Cup</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PUT_ALL__CUP = 0;

  /**
   * The number of structural features of the '<em>Put All</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PUT_ALL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.mymix.impl.PutImpl <em>Put</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.mymix.impl.PutImpl
   * @see org.xtext.example.mydsl.mymix.impl.MymixPackageImpl#getPut()
   * @generated
   */
  int PUT = 7;

  /**
   * The feature id for the '<em><b>Quantity</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PUT__QUANTITY = 0;

  /**
   * The feature id for the '<em><b>Cup</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PUT__CUP = 1;

  /**
   * The feature id for the '<em><b>Filter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PUT__FILTER = 2;

  /**
   * The number of structural features of the '<em>Put</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PUT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.mymix.impl.CheckImpl <em>Check</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.mymix.impl.CheckImpl
   * @see org.xtext.example.mydsl.mymix.impl.MymixPackageImpl#getCheck()
   * @generated
   */
  int CHECK = 8;

  /**
   * The feature id for the '<em><b>Cup</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECK__CUP = OPERATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Quantity</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECK__QUANTITY = OPERATION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Check</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECK_FEATURE_COUNT = OPERATION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.mymix.impl.WaitImpl <em>Wait</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.mymix.impl.WaitImpl
   * @see org.xtext.example.mydsl.mymix.impl.MymixPackageImpl#getWait()
   * @generated
   */
  int WAIT = 9;

  /**
   * The feature id for the '<em><b>Time</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WAIT__TIME = OPERATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Wait</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WAIT_FEATURE_COUNT = OPERATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.mymix.impl.ResultImpl <em>Result</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.mymix.impl.ResultImpl
   * @see org.xtext.example.mydsl.mymix.impl.MymixPackageImpl#getResult()
   * @generated
   */
  int RESULT = 10;

  /**
   * The feature id for the '<em><b>Cup</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESULT__CUP = 0;

  /**
   * The number of structural features of the '<em>Result</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESULT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.mymix.impl.FilterImpl <em>Filter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.mymix.impl.FilterImpl
   * @see org.xtext.example.mydsl.mymix.impl.MymixPackageImpl#getFilter()
   * @generated
   */
  int FILTER = 11;

  /**
   * The feature id for the '<em><b>Filter</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILTER__FILTER = 0;

  /**
   * The number of structural features of the '<em>Filter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILTER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.mymix.impl.CupImpl <em>Cup</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.mymix.impl.CupImpl
   * @see org.xtext.example.mydsl.mymix.impl.MymixPackageImpl#getCup()
   * @generated
   */
  int CUP = 12;

  /**
   * The feature id for the '<em><b>Cup</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUP__CUP = 0;

  /**
   * The number of structural features of the '<em>Cup</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUP_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.mymix.impl.QuantityImpl <em>Quantity</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.mymix.impl.QuantityImpl
   * @see org.xtext.example.mydsl.mymix.impl.MymixPackageImpl#getQuantity()
   * @generated
   */
  int QUANTITY = 13;

  /**
   * The feature id for the '<em><b>Quantity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUANTITY__QUANTITY = 0;

  /**
   * The number of structural features of the '<em>Quantity</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUANTITY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.mymix.impl.TimeImpl <em>Time</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.mymix.impl.TimeImpl
   * @see org.xtext.example.mydsl.mymix.impl.MymixPackageImpl#getTime()
   * @generated
   */
  int TIME = 14;

  /**
   * The feature id for the '<em><b>Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME__TIME = 0;

  /**
   * The number of structural features of the '<em>Time</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.mymix.Device <em>Device</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Device</em>'.
   * @see org.xtext.example.mydsl.mymix.Device
   * @generated
   */
  EClass getDevice();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.mymix.Device#getProcedures <em>Procedures</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Procedures</em>'.
   * @see org.xtext.example.mydsl.mymix.Device#getProcedures()
   * @see #getDevice()
   * @generated
   */
  EReference getDevice_Procedures();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.mymix.Procedure <em>Procedure</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Procedure</em>'.
   * @see org.xtext.example.mydsl.mymix.Procedure
   * @generated
   */
  EClass getProcedure();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.mymix.Procedure#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.mymix.Procedure#getName()
   * @see #getProcedure()
   * @generated
   */
  EAttribute getProcedure_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.mymix.Procedure#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Body</em>'.
   * @see org.xtext.example.mydsl.mymix.Procedure#getBody()
   * @see #getProcedure()
   * @generated
   */
  EReference getProcedure_Body();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.mymix.Procedure#getResult <em>Result</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Result</em>'.
   * @see org.xtext.example.mydsl.mymix.Procedure#getResult()
   * @see #getProcedure()
   * @generated
   */
  EReference getProcedure_Result();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.mymix.Operation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operation</em>'.
   * @see org.xtext.example.mydsl.mymix.Operation
   * @generated
   */
  EClass getOperation();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.mymix.TakeStuff <em>Take Stuff</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Take Stuff</em>'.
   * @see org.xtext.example.mydsl.mymix.TakeStuff
   * @generated
   */
  EClass getTakeStuff();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.mymix.TakeStuff#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Op</em>'.
   * @see org.xtext.example.mydsl.mymix.TakeStuff#getOp()
   * @see #getTakeStuff()
   * @generated
   */
  EReference getTakeStuff_Op();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.mymix.TakeStuff#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Body</em>'.
   * @see org.xtext.example.mydsl.mymix.TakeStuff#getBody()
   * @see #getTakeStuff()
   * @generated
   */
  EReference getTakeStuff_Body();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.mymix.Take <em>Take</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Take</em>'.
   * @see org.xtext.example.mydsl.mymix.Take
   * @generated
   */
  EClass getTake();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.mymix.Take#getQuantity <em>Quantity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Quantity</em>'.
   * @see org.xtext.example.mydsl.mymix.Take#getQuantity()
   * @see #getTake()
   * @generated
   */
  EReference getTake_Quantity();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.mymix.Take#getCup <em>Cup</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cup</em>'.
   * @see org.xtext.example.mydsl.mymix.Take#getCup()
   * @see #getTake()
   * @generated
   */
  EReference getTake_Cup();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.mymix.Take#getFilter <em>Filter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Filter</em>'.
   * @see org.xtext.example.mydsl.mymix.Take#getFilter()
   * @see #getTake()
   * @generated
   */
  EReference getTake_Filter();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.mymix.PutSome <em>Put Some</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Put Some</em>'.
   * @see org.xtext.example.mydsl.mymix.PutSome
   * @generated
   */
  EClass getPutSome();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.mymix.PutSome#getWait <em>Wait</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Wait</em>'.
   * @see org.xtext.example.mydsl.mymix.PutSome#getWait()
   * @see #getPutSome()
   * @generated
   */
  EReference getPutSome_Wait();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.mymix.PutSome#getPut <em>Put</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Put</em>'.
   * @see org.xtext.example.mydsl.mymix.PutSome#getPut()
   * @see #getPutSome()
   * @generated
   */
  EReference getPutSome_Put();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.mymix.PutAll <em>Put All</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Put All</em>'.
   * @see org.xtext.example.mydsl.mymix.PutAll
   * @generated
   */
  EClass getPutAll();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.mymix.PutAll#getCup <em>Cup</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cup</em>'.
   * @see org.xtext.example.mydsl.mymix.PutAll#getCup()
   * @see #getPutAll()
   * @generated
   */
  EReference getPutAll_Cup();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.mymix.Put <em>Put</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Put</em>'.
   * @see org.xtext.example.mydsl.mymix.Put
   * @generated
   */
  EClass getPut();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.mymix.Put#getQuantity <em>Quantity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Quantity</em>'.
   * @see org.xtext.example.mydsl.mymix.Put#getQuantity()
   * @see #getPut()
   * @generated
   */
  EReference getPut_Quantity();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.mymix.Put#getCup <em>Cup</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cup</em>'.
   * @see org.xtext.example.mydsl.mymix.Put#getCup()
   * @see #getPut()
   * @generated
   */
  EReference getPut_Cup();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.mymix.Put#getFilter <em>Filter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Filter</em>'.
   * @see org.xtext.example.mydsl.mymix.Put#getFilter()
   * @see #getPut()
   * @generated
   */
  EReference getPut_Filter();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.mymix.Check <em>Check</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Check</em>'.
   * @see org.xtext.example.mydsl.mymix.Check
   * @generated
   */
  EClass getCheck();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.mymix.Check#getCup <em>Cup</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cup</em>'.
   * @see org.xtext.example.mydsl.mymix.Check#getCup()
   * @see #getCheck()
   * @generated
   */
  EReference getCheck_Cup();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.mymix.Check#getQuantity <em>Quantity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Quantity</em>'.
   * @see org.xtext.example.mydsl.mymix.Check#getQuantity()
   * @see #getCheck()
   * @generated
   */
  EReference getCheck_Quantity();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.mymix.Wait <em>Wait</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Wait</em>'.
   * @see org.xtext.example.mydsl.mymix.Wait
   * @generated
   */
  EClass getWait();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.mymix.Wait#getTime <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Time</em>'.
   * @see org.xtext.example.mydsl.mymix.Wait#getTime()
   * @see #getWait()
   * @generated
   */
  EReference getWait_Time();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.mymix.Result <em>Result</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Result</em>'.
   * @see org.xtext.example.mydsl.mymix.Result
   * @generated
   */
  EClass getResult();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.mymix.Result#getCup <em>Cup</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cup</em>'.
   * @see org.xtext.example.mydsl.mymix.Result#getCup()
   * @see #getResult()
   * @generated
   */
  EReference getResult_Cup();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.mymix.Filter <em>Filter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Filter</em>'.
   * @see org.xtext.example.mydsl.mymix.Filter
   * @generated
   */
  EClass getFilter();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.mymix.Filter#getFilter <em>Filter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Filter</em>'.
   * @see org.xtext.example.mydsl.mymix.Filter#getFilter()
   * @see #getFilter()
   * @generated
   */
  EAttribute getFilter_Filter();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.mymix.Cup <em>Cup</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cup</em>'.
   * @see org.xtext.example.mydsl.mymix.Cup
   * @generated
   */
  EClass getCup();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.mymix.Cup#getCup <em>Cup</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Cup</em>'.
   * @see org.xtext.example.mydsl.mymix.Cup#getCup()
   * @see #getCup()
   * @generated
   */
  EAttribute getCup_Cup();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.mymix.Quantity <em>Quantity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Quantity</em>'.
   * @see org.xtext.example.mydsl.mymix.Quantity
   * @generated
   */
  EClass getQuantity();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.mymix.Quantity#getQuantity <em>Quantity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Quantity</em>'.
   * @see org.xtext.example.mydsl.mymix.Quantity#getQuantity()
   * @see #getQuantity()
   * @generated
   */
  EAttribute getQuantity_Quantity();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.mymix.Time <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Time</em>'.
   * @see org.xtext.example.mydsl.mymix.Time
   * @generated
   */
  EClass getTime();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.mymix.Time#getTime <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Time</em>'.
   * @see org.xtext.example.mydsl.mymix.Time#getTime()
   * @see #getTime()
   * @generated
   */
  EAttribute getTime_Time();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MymixFactory getMymixFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.mymix.impl.DeviceImpl <em>Device</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.mymix.impl.DeviceImpl
     * @see org.xtext.example.mydsl.mymix.impl.MymixPackageImpl#getDevice()
     * @generated
     */
    EClass DEVICE = eINSTANCE.getDevice();

    /**
     * The meta object literal for the '<em><b>Procedures</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEVICE__PROCEDURES = eINSTANCE.getDevice_Procedures();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.mymix.impl.ProcedureImpl <em>Procedure</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.mymix.impl.ProcedureImpl
     * @see org.xtext.example.mydsl.mymix.impl.MymixPackageImpl#getProcedure()
     * @generated
     */
    EClass PROCEDURE = eINSTANCE.getProcedure();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROCEDURE__NAME = eINSTANCE.getProcedure_Name();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROCEDURE__BODY = eINSTANCE.getProcedure_Body();

    /**
     * The meta object literal for the '<em><b>Result</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROCEDURE__RESULT = eINSTANCE.getProcedure_Result();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.mymix.impl.OperationImpl <em>Operation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.mymix.impl.OperationImpl
     * @see org.xtext.example.mydsl.mymix.impl.MymixPackageImpl#getOperation()
     * @generated
     */
    EClass OPERATION = eINSTANCE.getOperation();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.mymix.impl.TakeStuffImpl <em>Take Stuff</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.mymix.impl.TakeStuffImpl
     * @see org.xtext.example.mydsl.mymix.impl.MymixPackageImpl#getTakeStuff()
     * @generated
     */
    EClass TAKE_STUFF = eINSTANCE.getTakeStuff();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TAKE_STUFF__OP = eINSTANCE.getTakeStuff_Op();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TAKE_STUFF__BODY = eINSTANCE.getTakeStuff_Body();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.mymix.impl.TakeImpl <em>Take</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.mymix.impl.TakeImpl
     * @see org.xtext.example.mydsl.mymix.impl.MymixPackageImpl#getTake()
     * @generated
     */
    EClass TAKE = eINSTANCE.getTake();

    /**
     * The meta object literal for the '<em><b>Quantity</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TAKE__QUANTITY = eINSTANCE.getTake_Quantity();

    /**
     * The meta object literal for the '<em><b>Cup</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TAKE__CUP = eINSTANCE.getTake_Cup();

    /**
     * The meta object literal for the '<em><b>Filter</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TAKE__FILTER = eINSTANCE.getTake_Filter();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.mymix.impl.PutSomeImpl <em>Put Some</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.mymix.impl.PutSomeImpl
     * @see org.xtext.example.mydsl.mymix.impl.MymixPackageImpl#getPutSome()
     * @generated
     */
    EClass PUT_SOME = eINSTANCE.getPutSome();

    /**
     * The meta object literal for the '<em><b>Wait</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PUT_SOME__WAIT = eINSTANCE.getPutSome_Wait();

    /**
     * The meta object literal for the '<em><b>Put</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PUT_SOME__PUT = eINSTANCE.getPutSome_Put();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.mymix.impl.PutAllImpl <em>Put All</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.mymix.impl.PutAllImpl
     * @see org.xtext.example.mydsl.mymix.impl.MymixPackageImpl#getPutAll()
     * @generated
     */
    EClass PUT_ALL = eINSTANCE.getPutAll();

    /**
     * The meta object literal for the '<em><b>Cup</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PUT_ALL__CUP = eINSTANCE.getPutAll_Cup();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.mymix.impl.PutImpl <em>Put</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.mymix.impl.PutImpl
     * @see org.xtext.example.mydsl.mymix.impl.MymixPackageImpl#getPut()
     * @generated
     */
    EClass PUT = eINSTANCE.getPut();

    /**
     * The meta object literal for the '<em><b>Quantity</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PUT__QUANTITY = eINSTANCE.getPut_Quantity();

    /**
     * The meta object literal for the '<em><b>Cup</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PUT__CUP = eINSTANCE.getPut_Cup();

    /**
     * The meta object literal for the '<em><b>Filter</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PUT__FILTER = eINSTANCE.getPut_Filter();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.mymix.impl.CheckImpl <em>Check</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.mymix.impl.CheckImpl
     * @see org.xtext.example.mydsl.mymix.impl.MymixPackageImpl#getCheck()
     * @generated
     */
    EClass CHECK = eINSTANCE.getCheck();

    /**
     * The meta object literal for the '<em><b>Cup</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHECK__CUP = eINSTANCE.getCheck_Cup();

    /**
     * The meta object literal for the '<em><b>Quantity</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHECK__QUANTITY = eINSTANCE.getCheck_Quantity();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.mymix.impl.WaitImpl <em>Wait</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.mymix.impl.WaitImpl
     * @see org.xtext.example.mydsl.mymix.impl.MymixPackageImpl#getWait()
     * @generated
     */
    EClass WAIT = eINSTANCE.getWait();

    /**
     * The meta object literal for the '<em><b>Time</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WAIT__TIME = eINSTANCE.getWait_Time();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.mymix.impl.ResultImpl <em>Result</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.mymix.impl.ResultImpl
     * @see org.xtext.example.mydsl.mymix.impl.MymixPackageImpl#getResult()
     * @generated
     */
    EClass RESULT = eINSTANCE.getResult();

    /**
     * The meta object literal for the '<em><b>Cup</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RESULT__CUP = eINSTANCE.getResult_Cup();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.mymix.impl.FilterImpl <em>Filter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.mymix.impl.FilterImpl
     * @see org.xtext.example.mydsl.mymix.impl.MymixPackageImpl#getFilter()
     * @generated
     */
    EClass FILTER = eINSTANCE.getFilter();

    /**
     * The meta object literal for the '<em><b>Filter</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FILTER__FILTER = eINSTANCE.getFilter_Filter();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.mymix.impl.CupImpl <em>Cup</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.mymix.impl.CupImpl
     * @see org.xtext.example.mydsl.mymix.impl.MymixPackageImpl#getCup()
     * @generated
     */
    EClass CUP = eINSTANCE.getCup();

    /**
     * The meta object literal for the '<em><b>Cup</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CUP__CUP = eINSTANCE.getCup_Cup();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.mymix.impl.QuantityImpl <em>Quantity</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.mymix.impl.QuantityImpl
     * @see org.xtext.example.mydsl.mymix.impl.MymixPackageImpl#getQuantity()
     * @generated
     */
    EClass QUANTITY = eINSTANCE.getQuantity();

    /**
     * The meta object literal for the '<em><b>Quantity</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute QUANTITY__QUANTITY = eINSTANCE.getQuantity_Quantity();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.mymix.impl.TimeImpl <em>Time</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.mymix.impl.TimeImpl
     * @see org.xtext.example.mydsl.mymix.impl.MymixPackageImpl#getTime()
     * @generated
     */
    EClass TIME = eINSTANCE.getTime();

    /**
     * The meta object literal for the '<em><b>Time</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIME__TIME = eINSTANCE.getTime_Time();

  }

} //MymixPackage
