/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.mymix;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Put Some</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.mymix.PutSome#getWait <em>Wait</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.mymix.PutSome#getPut <em>Put</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.mymix.MymixPackage#getPutSome()
 * @model
 * @generated
 */
public interface PutSome extends EObject
{
  /**
   * Returns the value of the '<em><b>Wait</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.mymix.Wait}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Wait</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Wait</em>' containment reference list.
   * @see org.xtext.example.mydsl.mymix.MymixPackage#getPutSome_Wait()
   * @model containment="true"
   * @generated
   */
  EList<Wait> getWait();

  /**
   * Returns the value of the '<em><b>Put</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.mymix.Put}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Put</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Put</em>' containment reference list.
   * @see org.xtext.example.mydsl.mymix.MymixPackage#getPutSome_Put()
   * @model containment="true"
   * @generated
   */
  EList<Put> getPut();

} // PutSome
