/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import org.xtext.example.mix.ui.internal.MixActivator;

public class MymixUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MixActivator.getInstance().getInjector("org.xtext.example.mydsl.Mymix");
	}

}
